server:
  port: 8081
  servlet:
    session:
      cookie:
        name: BIONICPRO_SESSION
        http-only: true
        secure: true
        same-site: strict
        path: /
  error:
    include-message: always

spring:
  application:
    name: bionicpro-auth
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000
  session:
    store-type: redis
    timeout: 10m
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bionicpro-auth-backend
            client-secret: ${BIONICPRO_AUTH_BACKEND_SECRET}
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/auth/callback"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/reports-realm
            authorization-uri: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/token
            jwk-set-uri: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/certs
            user-name-attribute: sub

bff:
  keycloak:
    issuer-uri: http://keycloak:8080/realms/reports-realm
    token-uri: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/token
    logout-uri: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/logout
  frontend:
    redirect-uri: http://localhost:3000
  session:
    cookie-domain: localhost
    cookie-path: /
  encryption:
    key: ${BFF_ENCRYPTION_KEY}

logging:
  level:
    root: INFO
    com.bionicpro: DEBUG
    org.springframework.security: DEBUG
    org.springframework.session: DEBUG